namespace Networking.mpp.networking.rpcprotocol;
public enum RequestType
{
    LOGIN,
    INSCRIERE_PARTICIPANT,
    GET_ALL_CURSE,
    LIST_DTO_CURSE,
    GET_ALL_PARTICIPANTI,
    CAUTA_PARTICIPANTI_ECHIPA,
    FIND_ECHIPA_BY_NUME,
    ADAUGA_ECHIPA,
    FIND_NR_PART_BY_CURSA,
    GET_ALL_PARTICIPANT_CURSA,
    ADAUGA_PARTICIPANT_LA_CURSA,
    FIND_PARTICIPANT_BY_NUME,
    LOGOUT
}